# Site settings
title: Start Jekyll
email: adrian.m.ryan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first Jekyll site, made following the tutorial at http://www.taniarascia.com/make-a-static-website-with-jekyll/
baseurl: "/page1"
url: "http://taniarascia.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM